# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.12.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.12.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/manasichaturvedi/Mihir/2048.cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/manasichaturvedi/Mihir/2048.cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.12.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.12.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/manasichaturvedi/Mihir/2048.cpp/CMakeFiles /Users/manasichaturvedi/Mihir/2048.cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/manasichaturvedi/Mihir/2048.cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 2048

# Build rule for target.
2048: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 2048
.PHONY : 2048

# fast build rule for target.
2048/fast:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/build
.PHONY : 2048/fast

2048.o: 2048.cpp.o

.PHONY : 2048.o

# target to build an object file
2048.cpp.o:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/2048.cpp.o
.PHONY : 2048.cpp.o

2048.i: 2048.cpp.i

.PHONY : 2048.i

# target to preprocess a source file
2048.cpp.i:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/2048.cpp.i
.PHONY : 2048.cpp.i

2048.s: 2048.cpp.s

.PHONY : 2048.s

# target to generate assembly for a file
2048.cpp.s:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/2048.cpp.s
.PHONY : 2048.cpp.s

game.o: game.cpp.o

.PHONY : game.o

# target to build an object file
game.cpp.o:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/game.cpp.o
.PHONY : game.cpp.o

game.i: game.cpp.i

.PHONY : game.i

# target to preprocess a source file
game.cpp.i:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/game.cpp.i
.PHONY : game.cpp.i

game.s: game.cpp.s

.PHONY : game.s

# target to generate assembly for a file
game.cpp.s:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/game.cpp.s
.PHONY : game.cpp.s

global.o: global.cpp.o

.PHONY : global.o

# target to build an object file
global.cpp.o:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/global.cpp.o
.PHONY : global.cpp.o

global.i: global.cpp.i

.PHONY : global.i

# target to preprocess a source file
global.cpp.i:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/global.cpp.i
.PHONY : global.cpp.i

global.s: global.cpp.s

.PHONY : global.s

# target to generate assembly for a file
global.cpp.s:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/global.cpp.s
.PHONY : global.cpp.s

menu.o: menu.cpp.o

.PHONY : menu.o

# target to build an object file
menu.cpp.o:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/menu.cpp.o
.PHONY : menu.cpp.o

menu.i: menu.cpp.i

.PHONY : menu.i

# target to preprocess a source file
menu.cpp.i:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/menu.cpp.i
.PHONY : menu.cpp.i

menu.s: menu.cpp.s

.PHONY : menu.s

# target to generate assembly for a file
menu.cpp.s:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/menu.cpp.s
.PHONY : menu.cpp.s

scores.o: scores.cpp.o

.PHONY : scores.o

# target to build an object file
scores.cpp.o:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/scores.cpp.o
.PHONY : scores.cpp.o

scores.i: scores.cpp.i

.PHONY : scores.i

# target to preprocess a source file
scores.cpp.i:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/scores.cpp.i
.PHONY : scores.cpp.i

scores.s: scores.cpp.s

.PHONY : scores.s

# target to generate assembly for a file
scores.cpp.s:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/scores.cpp.s
.PHONY : scores.cpp.s

statistics.o: statistics.cpp.o

.PHONY : statistics.o

# target to build an object file
statistics.cpp.o:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/statistics.cpp.o
.PHONY : statistics.cpp.o

statistics.i: statistics.cpp.i

.PHONY : statistics.i

# target to preprocess a source file
statistics.cpp.i:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/statistics.cpp.i
.PHONY : statistics.cpp.i

statistics.s: statistics.cpp.s

.PHONY : statistics.s

# target to generate assembly for a file
statistics.cpp.s:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/statistics.cpp.s
.PHONY : statistics.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... 2048"
	@echo "... 2048.o"
	@echo "... 2048.i"
	@echo "... 2048.s"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... global.o"
	@echo "... global.i"
	@echo "... global.s"
	@echo "... menu.o"
	@echo "... menu.i"
	@echo "... menu.s"
	@echo "... scores.o"
	@echo "... scores.i"
	@echo "... scores.s"
	@echo "... statistics.o"
	@echo "... statistics.i"
	@echo "... statistics.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

